# Project: polynomial
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../Source/Function.o ../Polynomial/Polynomial/Polynomial.o
LINKOBJ  = ../Source/Function.o ../Polynomial/Polynomial/Polynomial.o
LIBS     = -L"E:/DEV-c/Dev-Cpp/MinGW64/lib" -L"E:/DEV-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/DEV-c/Dev-Cpp/MinGW64/include" -I"E:/DEV-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DEV-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/root/Desktop/program/C++/data structure/Polynomial/Header"
CXXINCS  = -I"E:/DEV-c/Dev-Cpp/MinGW64/include" -I"E:/DEV-c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DEV-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/DEV-c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++" -I"C:/Users/root/Desktop/program/C++/data structure/Polynomial/Header"
BIN      = polynomial.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../Source/Function.o: ../Source/Function.cpp
	$(CPP) -c ../Source/Function.cpp -o ../Source/Function.o $(CXXFLAGS)

../Polynomial/Polynomial/Polynomial.o: ../Polynomial/Polynomial/Polynomial.cpp
	$(CPP) -c ../Polynomial/Polynomial/Polynomial.cpp -o ../Polynomial/Polynomial/Polynomial.o $(CXXFLAGS)
